sudo: required

language: ruby
rvm:
  - 2.2.2

git:
  depth: 1

branches:
  only:
    - travis_ci

services:
  - postgresql
addons:
  apt:
    packages:
      - postgresql-contrib-9.4 # hstore, cube, earthdistance
      - postgresql-9.4-plv8    # stored procedures in JavaScript
  postgresql: "9.4"

before_script:
  - cp .env.example .env.test
  - bundle exec rake db:drop db:create db:migrate db:test:prepare

script:
  - bundle exec rake spec
  - bundle exec rake jasmine:ci